#!/bin/bash

set -x

if [ ! "$ROOT_CHECK" = "0" ]; then
   if [ "$(id -u)" != "0" ]; then
       echo "${red}${bold}ERROR: This must be run as root (sudo)!${reset}"
       exit 1
   else
       true "INFO: Script running as root."
   fi
fi

apt-get update
apt-get install haveged

cat /usr/sbin/policy-rc.d || true

service haveged restart || true

service haveged start || true

service haveged status || true

/etc/init.d/haveged restart || true

/etc/init.d/haveged start || true

/etc/init.d/haveged status || true
